version: "3.9"
services:
  frr-100-r10:
    image: quay.io/frrouting/frr:10.2.2
    container_name: frr-100-r10
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      net100:
        ipv4_address: 10.0.100.10
      net101:
        ipv4_address: 10.0.101.100
    volumes:
      - ./frr-100-r10/daemons:/etc/frr/daemons
      - ./frr-100-r10/frr.conf:/etc/frr/frr.conf
      - ./frr-100-r10/start_frr.sh:/etc/frr/start_frr.sh
      - ./frr-100-r10/vtysh.conf:/etc/frr/vtysh.conf
      - ./frr-100-r10/zebra.conf:/etc/frr/zebra.conf
    command: "/bin/bash /etc/frr/start_frr.sh"

  frr-200-r10:
    image: quay.io/frrouting/frr:10.2.2
    container_name: frr-200-r10
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      net200:
        ipv4_address: 10.0.200.10
      net101:
        ipv4_address: 10.0.101.200
    volumes:
      - ./frr-200-r10/daemons:/etc/frr/daemons
      - ./frr-200-r10/frr.conf:/etc/frr/frr.conf
      - ./frr-200-r10/start_frr.sh:/etc/frr/start_frr.sh
      - ./frr-200-r10/vtysh.conf:/etc/frr/vtysh.conf
      - ./frr-200-r10/zebra.conf:/etc/frr/zebra.conf
    command: "/bin/bash /etc/frr/start_frr.sh"

networks:
  net100:
    ipam:
      config:
        - subnet: 10.0.100.0/24
  net101:
    ipam:
      config:
        - subnet: 10.0.101.0/24
  net200:
    ipam:
      config:
        - subnet: 10.0.200.0/24