version: "3"
services:
  r1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net100:
        ipv4_address: 192.168.100.1
      net101:
        ipv4_address: 192.168.101.1
    volumes:
      - ./frr100:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"

  r2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net101:
        ipv4_address: 192.168.101.2
      net200:
        ipv4_address: 192.168.200.2
    volumes:
      - ./frr200:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"

networks:
  net100:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  net101:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
  net200:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
